# Generated by Django 5.2.4 on 2025-07-20 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название партнёра", max_length=255)),
                ("email", models.EmailField(help_text="Email для связи", max_length=254)),
                ("country", models.CharField(help_text="Страна, где расположен партнёр", max_length=100)),
                ("city", models.CharField(help_text="Город, где расположен партнёр", max_length=100)),
                ("street", models.CharField(help_text="Улица партнёра", max_length=100)),
                ("house_number", models.CharField(help_text="Номер дома", max_length=10)),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2, help_text="Сумма задолженности перед поставщиком", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="Дата и время создания записи")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик — другой элемент сети, от которого получаются товары",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="networks.partner",
                    ),
                ),
            ],
        ),
    ]
