# Generated by Django 5.2.4 on 2025-07-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название продукта", max_length=255)),
                ("model", models.CharField(help_text="Модель устройства", max_length=100)),
                ("release_date", models.DateField(help_text="Дата выхода продукта на рынок")),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Партнёр, у которого продаётся продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="networks.partner",
                    ),
                ),
            ],
        ),
    ]
