# Generated by Django 5.2.4 on 2025-07-24 19:58

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="debt_to_supplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Сумма задолженности перед поставщиком",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.CheckConstraint(
                condition=models.Q(("debt_to_supplier__gte", 0)), name="debt_non_negative"
            ),
        ),
    ]
