# Generated by Django 5.2.4 on 2025-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0003_alter_partner_debt_to_supplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="city",
            field=models.CharField(db_index=True, help_text="Город, где расположен партнёр", max_length=100),
        ),
        migrations.AlterField(
            model_name="partner",
            name="country",
            field=models.CharField(db_index=True, help_text="Страна, где расположен партнёр", max_length=100),
        ),
        migrations.AlterField(
            model_name="partner",
            name="email",
            field=models.EmailField(db_index=True, help_text="Email для связи", max_length=254),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["country"], name="networks_pa_country_b4f27a_idx"),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(fields=["city", "name"], name="networks_pa_city_5c4b98_idx"),
        ),
    ]
