# Generated by Django 5.2.4 on 2025-07-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0004_alter_partner_city_alter_partner_country_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="partner",
            name="networks_pa_country_b4f27a_idx",
        ),
        migrations.AlterField(
            model_name="partner",
            name="city",
            field=models.CharField(help_text="Город, где расположен партнёр", max_length=100),
        ),
        migrations.AlterField(
            model_name="partner",
            name="country",
            field=models.CharField(help_text="Страна, где расположен партнёр", max_length=100),
        ),
    ]
